src/constants/index.ts
src/schemas/gql/graphql.ts

This PR change `DEFAULT_TCP_CHECK_HTTP_METHOD` from `CONNECT` to `HEAD`
Related https://github.com/daeuniverse/dae/pull/137

fix(config): change `DEFAULT_TCP_CHECK_HTTP_METHOD`

---

.dockerignore
.github/workflows/build.yml
.github/workflows/publish-docker-image.yml
.github/workflows/publish-gh-pages.yml
Caddyfile
Dockerfile
Makefile

This PR adds a dedicated workflow file to support `build and publish daed docker image with geosite/geoip` within github ci
Only build linux/amd64 for now

ci: build and publish daed docker image with geosite/geoip

---

.github/workflows/build.yml

This PR aims to fix a issue about runtime error as follows, `CGO` related
```
daed: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by daed)
```

fix: /lib64/libc.so.6: version `GLIBC_2.32' not found

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support-request.md
.github/PULL_REQUEST_TEMPLATE.md

- chore: add issue templates
- chore: add pull request template

chore: add issue,pull_request templates

---

.editorconfig
.github/PULL_REQUEST_TEMPLATE.md

chore: add .editorconfig

---

src/constants/index.ts

set `DEFAULT_AUTO_CONFIG_KERNEL_PARAMETER` to true, this can eliminate the requirement to do a manual sysctl.conf configuration by default.
- feat: set `DEFAULT_AUTO_CONFIG_KERNEL_PARAMETER` to true
None

feat: set `DEFAULT_AUTO_CONFIG_KERNEL_PARAMETER` to true

---

Makefile

Customize the independent app name by setting the APPNAME environment variable.
See https://github.com/daeuniverse/dae-wing/pull/24

build: set independent app name

---

.github/workflows/sync-upstream-source.yml

Change synchronize upstream repositories from creating branch only to creating pull request
- ci(sync): sync create pull request
None

ci(sync): sync create pull request

---

src/components/SimpleCard.tsx

Hide remove button of rule card if this rule is currently selected, this can eliminate issues where user can have a ghost rule when the service is still running.
- feat(rules): hide remove button if selected
None

feat(rules): hide remove button if selected

---

src/constants/index.ts
src/pages/MainLayout.tsx

- Rename default `config` to `global`
- Rename default `group` to `proxy`
- feat: rename default config (global) and group (proxy)
None

feat: rename default config (global) and group (proxy)

---

src/components/ConfigFormModal.tsx
src/i18n/locales/en.json
src/i18n/locales/zh-Hans.json

Previously, the tproxy port number input inside config modal has no upper and lower integer value limit, which doesnt align with the real-world TCP port number range (0 - 65535).
Also adds rich descriptive help texts for user inputs inside config form to help user understand what the config fields is doing
- feat(config): limit the tproxy port input range to `0 - 65535`
- feat(config): add descriptive help texts for user inputs
None

fix: limit the tproxy port input range, add descriptive help texts

---

.github/workflows/sync-upstream-source.yml

fix(sync-upstream-docs): do not use ref in checkout action

---

.github/workflows/build-nightly.yml
.github/workflows/build.yml
.gitignore
.gitmodules.d.mk
Makefile

Use `go mod cache` for fuller mod support.

chore: use go mod cache instead of go mod vendor

---

LICENSE
LICENSE-MIT
README.md

Refine LICENSE as mixed MIT/AGPL-3.0-only.

chore: refine license

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

Getting ready for initial release. By default, the release workflow is designed to be triggered ONLY by `push.tag` event. The reason why I propose to do it in such a way is that it may better fit into the `automatic release` cycle in the future.
> **Note**: Instead of us manually push a release tag, @daebot will do it for us in the `next` release cycle - already planned in our roadmap.
- ci: separate release build from main_stream build
https://github.com/daeuniverse/daed-1/actions/runs/5304376937
NA.

ci: separate release build from main_stream build

---

.github/workflows/build-nightly.yml

As the title suggests, this PR specify fetch-depth: 0 for checkout step before getting version info from git history
- ci(build-nightly): add fetch-depth: 0
None

ci(build-nightly): add fetch-depth: 0

---

src/components/ConfigFormModal.tsx
src/components/GroupFormModal.tsx
src/components/SelectItemWithDescription.tsx
src/i18n/locales/en.json
src/i18n/locales/zh-Hans.json

This PR adds description text for group policies, to help user understand what each group policy can do
- feat: add description text for group policies
None

feat: add description text for group policies

---

src/apis/query.ts
src/components/ConfigFormModal.tsx
src/schemas/gql/gql.ts
src/schemas/gql/graphql.ts

This PR adds a feature, show interface ip addresses in interface field select component
Here's a preview about this feature
- feat(config): show interface ip addresses in interface select
None

feat(config): show interface ip addresses in interface select

---

src/constants/index.ts

After reading the feature description of [allow insecure](https://github.com/daeuniverse/dae/blob/main/example.dae#L82), i think we should disable it by default.
- fix(config): disable allow insecure by default
None

fix(config): disable allow insecure by default

---

src/components/FormActions.tsx
src/components/Header.tsx
src/components/ImportResourceFormModal.tsx
src/pages/Orchestrate.tsx

This PR adds loading state indicators for the following scenario
- update subscription
- run / suspense dae
- reload after modified state changes
- feat: add loading state indicators
None

feat: add loading state indicators

---

.github/workflows/sync-upstream.yml

Add `sync-upstream` workflow back, but this time, let's do NOT add the ~~broken~~ PR create action. Instead, let @daebot automate the PR creation for us.
- ci: add sync-upstream workflow
Try to reproduce the test scenario as much as I could...
1.1 checkout to a specific history commit in `dae-wing` submodule
1.2 kick off the `sync-upstream` workflow by pushing a commit to `ci-bot-experiment` origin/main
> **Note**: In the production case, we should use `dae-wing`.
1.3 create a PR on the fly
NA

ci: add sync-upstream workflow

---

src/components/SortableResourceBadge.tsx
src/pages/Orchestrate.tsx

This PR adds a feature, when user hover on a node inside of a group, it will show the tag name of the subscription it belongs to .
- feat(group): show subscription tag on node hover
None

feat(group): show subscription tag on node hover

---

src/components/DraggableSubscriptionNodeBadge.tsx
src/components/UpdateSubscriptionAction.tsx
src/pages/Orchestrate.tsx

Previously, every loading indicators will be spining when one of the subscriptions is updating, this PR fixes that.
Now it should be showing only on individual subscription updating.
- fix(subscription): loading indicator of update should show on individual subscription
None

fix(subscription): loading indicator of update

---

src/components/SelectItemWithDescription.tsx
src/pages/Orchestrate.tsx
src/utils/dnd-kit.ts

This PR made a feature change, reduces drag and drop area to resources container
- feat: restrict drag and drop area
None

feat: restrict drag and drop area

---

src/constants/index.ts

This PR adds tcp method to default googledns url
- fix: default googledns add tcp
None

fix: default googledns add tcp

---

src/apis/mutation.ts

When user remove a node or subscription (specifically, not within a group), if it's currently referenced by a group, the group still has that present. This PR fixes it by refreshing group list after removing nodes or subscriptions.
- fix(group): refresh after remove nodes/subs
None

fix(group): refresh after remove nodes/subs

---

src/components/DraggableResourceCard.tsx
src/pages/Orchestrate/Node.tsx

This PR adds a new feature, change the node protocol display, instead of card body, show the node protocol in card title, like the screenshot shows
- feat: show node protocol in card title
None

feat: show node protocol in card title

---

src/components/QRCodeModal.tsx
src/components/UpdateSubscriptionAction.tsx
src/pages/Orchestrate/Node.tsx
src/pages/Orchestrate/Subscription.tsx

This PR adds a new feature, render qrcode in canvas to allow user to save image
- feat: render qrcode in canvas to allow user to save image
None

feat: render qrcode in canvas to allow user to save image

---

package.json
pnpm-lock.yaml
src/components/PlainTextFormModal.tsx
src/constants/index.ts
src/main.tsx

This PR adds a new feature, use theme `github` as default monaco editor light theme
- feat: use theme `github` as default monaco editor light theme
- feat: add a 4 pixel border radius container to wrap editor
None

feat: use theme `github` as default monaco editor light theme

---

src/components/PlainTextFormModal.tsx
src/main.tsx

This PR adds code highlight support for routingA files, including dns and routing.
- feat(editor): add routingA code highlight
None

feat(editor): add routingA code highlight

---

src/constants/index.ts
src/main.tsx

This PR adds a new feature, allow editor to render a rule without quotes as tag.
- feat(editor): render tags
None

feat(editor): render tags

---

src/components/Header.tsx
src/pages/MainLayout.tsx

This PR adds a header icon link to github project, also adds a new footer section
- feat: add header icon link to github project, and a footer
None

feat: add header icon link to github project, and a footer

---

.github/workflows/generate-changelogs.yml
.github/workflows/prerelease.yml
package.json

As the title suggests, introduce the `generate-changelogs` workflow to make changelogs content management much easier.
Associated project: https://github.com/daeuniverse/changelogs-generator-action
- chore(package.json): bump up version to v0.1.0
- ci(prerelease): demise tag-based trigger; use distpatch trigger instead
- ci(changelogs): add generate-changelogs workflow
Test result is avilable in https://github.com/daeuniverse/daed/issues/103
https://github.com/daeuniverse/daed/actions/runs/5362304326/jobs/9729072058

ci: introduce generate-changelogs workflow

---

src/components/PlainTextFormModal.tsx
src/constants/index.ts

This PR makes plaintext modal fullscreen
- feat: make plaintext modal fullscreen
None

feat: make plaintext modal fullscreen

---

index.html

This PR makes a viewport meta tag change, disable zooming and panning on mobile
- feat: disable zooming and panning on mobile
None

feat: disable zooming and panning on mobile

---

src/components/ConfigFormModal.tsx
src/components/Header.tsx
src/components/PlainTextFormModal.tsx
src/pages/MainLayout.tsx

Previously, footer sits on top of modal overlay, causing misbehaved layout issue. This PR fixes it.
- fix: footer is floating above modal overlay
None

fix: footer is floating above modal overlay

---

src/components/PlainTextFormModal.tsx
src/constants/editor.ts
src/constants/index.ts
src/main.tsx
src/pages/Experiment.tsx

This PR attempts to fix a hard-to-catch issue, caret misplacement, here is the [upstream bug report](https://github.com/microsoft/monaco-editor/issues/3217)
See the reproduction link below
https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#XQAAAAIFBAAAAAAAAABBqQkHQ5NjdYzqEXhNewrSKZslyM_G2I4bTkHQYW1lB1MplPA6z0speGDFvgRIQQx0HI9zdEFZdk3ipJqwzu6RT44vPXZPcpCKxnvgE9TYAtuAi9VQr3EAhbQJCn4JPD8EaFYCtRcYWa8_pnHjN-uDjxrhmN3g8tmx0iWUz1zF7VMROnGNjfHj2TFmcBooqFj0KG-T22ZTMhTuebWAKwtN_PzaTmIn83sxr9iG_rCToVGZ0s8Aqq4FCtsWBjMFVvarCcsgdWatYDG40I2zD8RTtWuNHNnY7c7IoNZIQlbLuUY6eiWdTFPiXUP1O8oaah0Csz8RlRcIa1l9lhCgWLmDqqOL08Y3F0K8dVIo69eyZtcffV2oBXpdc3VTcdsCp1Y898LUMwBEQMRkIvbz7CBuaqOSacXtrQdqhAqjekP8a0fHRClj00Ayniiid1DDyNpyEfu6SGdPfBH6LkLC5i7FXsHHUvO1GnCc1irro7YZl39IXXoeMqNUFgbEUptiN43oiqtTzY …

fix: try fixing caret misplacement

---

.github/workflows/build.yml
.github/workflows/pr-build.yml
docs/getting-started.md

Mimic proposed changes in https://github.com/daeuniverse/dae/pull/183
- docs(getting-started): rename nightly build to pr-build
- refactor(workflow): rename build-nightly -> pr-build
- ci: add run_name followed by `#pr_number - pr_title @pr_ref:pr_sha`
- ci: add initial job to show pr context
- refactor(build): update workflow title from Build to Build (Stable)
- ci: make context an independent job
NA
https://github.com/daeuniverse/daed/actions/runs/5497492906

ci: refine pr-build workflow

---

.github/PULL_REQUEST_TEMPLATE.md

- chore(pr_template): add test result section
- fix: fix issue reference keyword
NA

chore(pr_template): add test result section

---

.github/workflows/generate-changelogs.yml

Replicate PR - https://github.com/daeuniverse/dae/pull/201
Prevent writing changelogs to GitHub issues by default.
- ci(generate-changelogs): set dry_run to true by default
NA
https://github.com/daeuniverse/dae-1/actions/runs/5508370825

ci(generate-changelogs): set dry_run to true by default

---

.github/workflows/sync-upstream.yml

- ci(sync-upstream): fix invalid downstream workflow ref
NA
NA

ci(sync-upstream): fix invalid downstream workflow ref

---

src/components/ConfigFormModal.tsx

This PR fixes a issue, instead of required, wan interface field should be optional
- fix: wan interface should be optional
None

fix: wan interface should be optional

---

src/components/ConfigureNodeFormModal/TuicForm.tsx
src/components/ConfigureNodeFormModal/V2rayForm.tsx
src/i18n/locales/en.json
src/i18n/locales/zh-Hans.json

This PR fixes a issue, add missing websocket path field input in configure node form modal
- fix(v2ray): add missing websocket path field
None

fix(v2ray): add missing websocket path field

---

.github/workflows/pr-build.yml

Integrate check runs to report build status.
Relevant workflows:
- https://github.com/daeuniverse/ci-seed-jobs/blob/master/core/daed/instantiate-check-runs/action.yml
- https://github.com/daeuniverse/ci-seed-jobs/blob/master/core/daed/report-check-run/action.yml
References:
- [Github API - Check Runs](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28)
- [About GitHub status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks)
- [Github checks API vs check runs vs check suites](https://stackoverflow.com/questions/67919168/github-checks-api-vs-check-runs-vs-check-suites)
- ci(pr-build): integrate check runs to report build status
- ci(pr-build): integrate individual …

ci(pr-build): integrate check runs to report build status

---

.github/workflows/pr-build.yml

Contributors outside of `daeuniverse` is NOT able to kick of the pr-build because insufficient permission to instantiate check-runs. This PR proposes changes to resolve it by skipping those `check-runs` related actions.
- ci/fix(pr-build): skip check-run related actions based on condition
NA
Scenario 1: contributor is a member of daeuniverse org
https://github.com/daeuniverse/daed/actions/runs/5561342029/jobs/10158963914
Scenario 2: contributor is outside of daeuniverse org
TBD.

ci/fix(pr-build): skip check-run related actions based on condition

---

.github/workflows/pr-build.yml

Add `pr.ready_for_review` trigger in `PR Build (Preview)`. It should trigger PR build when a drafted PR converts to `ready for review` state.
Ref: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=ready_for_review#pull_request
- ci(pr-build): add pr.ready_for_review trigger
NA
NA

ci(pr-build): add ready_for_review trigger

---

.github/workflows/pr-build.yml
install/friendly-filenames.json

As the title suggests. The idea is to drastically reduce build time.
- ci(pr-build): ONLY keep arm64, amd64 as build targets
- patch(friendly-filenames.json): add entry for amd64 
NA

ci(pr-build): ONLY keep arm64, amd64 as build targets

---

Makefile

https://paste.opensuse.org/pastes/48a22a1d153b

fix: avoid to install husky when not in a git repo

---

.github/workflows/build.yml
.github/workflows/pr-build.yml

Fix the issue where changes made to `wing (submodule)` do NOT trigger the build, pr-build workflow. 
- ci/fix(pr-build): fix submodule path trigger 
- ci/fix(build): fix submodule path trigger 
NA
https://github.com/daeuniverse/daed/actions/runs/5692285650

ci/fix(pr-build,build): fix submodule path trigger

---

src/components/ConfigureNodeFormModal/JuicityForm.tsx
src/constants/default.ts
src/constants/schema.ts
src/i18n/locales/en.json
src/i18n/locales/zh-Hans.json

add pinned_certchain_sha256 config in web panel.

feat: add juicity pinned_certchain_sha256 config

---

.github/workflows/pick-build.yml
Makefile

作为 core， dae 用户可以很方便的提前体验到令人激动的新功能，而 daed 要等待更久的链路同步时间: dae ->  dae-wing -> daed
这让使用daed的我们黯然神伤，我们也想要体验最新的功能 ！
虽然我们已经有了 [hack/checkout.sh](https:github.com/daeuniverse/daed/blob/main/hack/checkout.sh) 可以挑选分支进行本地构建。但是这对用户来说仍需要一定的成本，比如机器性能赢弱的编译可能会比较困难。
此 PR 添加了一个需手动触发的 workflow ，允许指定 commit id 或分支名进行构建，方便用户在daed 上提前体验 dae 令人激动的新功能
<!--- Attach test result here. --

ci: add pick-build workflow

---

.github/workflows/pick-build.yml

Because [hack/checkout.sh](https://github.com/wanlce/daed/blob/main/hack/checkout.sh) modifies wing and core, but not daed,`pick_build workflow` supports modification of daed, wing and dae at the same time, so it can be used simply and directly    
- [ x] The Pull Request has been fully tested

ci(pick): fix build error when daed is not main

---

.github/workflows/build.yml
.github/workflows/pick-build.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml

Since we have merged https://github.com/daeuniverse/daed/pull/233. There is no need to define `pie` in `BUILD_ARGS` explicitly.

chore: remove BUILD_ARGS in workflows

---

docs/getting-started.md

Some users don't know how to use systemd to start daed

docs: Added Debian, RedHat, openSUSE, installation instructions

---

docs/getting-started.md

docs(getting-started): make subtle changes

---

.dockerignore
Dockerfile
docker-compose.yml
docs/getting-started.md

This PR makes Dockerfile work out of box
see: https://github.com/daeuniverse/daed/issues/250 and https://github.com/daeuniverse/daed/issues/262
- chore/fix:upgrade llvm and clang version in Dockerfile (https://github.com/daeuniverse/daed/issues/250)
- build/fix(Dockerfile):fix "geoip.dat:file does not exist" (https://github.com/daeuniverse/daed/issues/262)
- Docs(getting-started): Add docker(https://github.com/daeuniverse/daed/issues/250#issuecomment-1703896541)
https://github.com/daeuniverse/daed/issues/250 
https://github.com/daeuniverse/daed/issues/262
works just fine

ci(Dockerfile): Dockerfile working out of box

---

docs/getting-started.md

No installation guide of daed on Arch Linux in ```docs/getting-started.md```.
- Add installation guide of daed on Arch Linux in ```docs/getting-started.md```.

docs/getting-started.md: add archlinux installation guide

---

.github/workflows/publish-docker-image.yml
Dockerfile
docs/getting-started.md
publish.Dockerfile

Thanks for your patience. Maybe this will help. Only the tested will be squashed into one commit and pushed here. I'll try not to close pr so frequently. Feel free to review my working status in my repo. 
- ci(docker): docker build once and push to multiple repos
- ci(docker): docker build and push with tags
- ci(docker): come back arm64 platform support (Experimental)
- ci(docker): publish dockerhub image
- ci(docker): action version upgrade
- ci(docker): multiple action trigger
- ci(docker): build with tag on dashboard
- ci(docker): i386, armv7 armv8 platform support (Experimental)
https://github.com/daeuniverse/daed/issues/280
https://github.com/daeuniverse/daed/pull/267
https://github.com/daeuniverse/daed/pull/286
[Action page](https://github.com/hero-intelligent/daed/actions/runs/6247 …

ci(docker): rework workflow (3rd time)

---

src/components/ConfigureNodeFormModal/Hysteria2Form.tsx
src/components/ConfigureNodeFormModal/index.tsx
src/constants/default.ts
src/constants/schema.ts
src/i18n/locales/en.json
src/i18n/locales/zh-Hans.json
src/utils/node.ts

Ref: https://v2.hysteria.network/docs/developers/URI-Scheme/

feat: add configure hysteria2 modal

---

src/components/ConfigureNodeFormModal/V2rayForm.tsx

Closes [[Bug Report] vmess 使用websocket时不支持配置Path参数](https://github.com/daeuniverse/dae-wing/issues/167)

fix(v2ray): vmess websocket path emty

---

docs/getting-started.md

The original package name `daed-bin-x64-v3` is ill-formed, which makes it removed from AUR. Therefore, it has been renamed to `daed-avx2-bin`.
Related commit: https://github.com/archlinuxcn/repo/commit/219e513c86bb762ec13a62c0f000f9073326c684
- Update package name of the AVX2-optimized binary package in archlinuxcn section of installation guide
- Add AVX2-optimized binary package to AUR section in installation guide
- Format the Arch Linux section in installation guide

docs: update archlinuxcn package name & add AVX2 package to AUR
