daeuniverse/daed

.vscode/extensions.json
.vscode/settings.json

chore: add i18n Ally extension

---

package.json
pnpm-lock.yaml
src/App.tsx
src/Home.tsx
src/i18n/locales/en.json
src/i18n/locales/zh-Hans.json

As the title suggests, this PR makes config card draggable and sortable.

feat: draggable config

---

.github/workflows/build-release.yml
.gitignore
.gitmodules
Makefile
install/daed.service

Add `Makefile` and `dae-wing` sumodule.
NOTICE: Not support multiple jobs yet.
Add release actions.

chore: makefile and release actions

---

.github/workflows/build.yml

Provides an automatically compiled Linux installation package for Debian, RedHat and Arch.
build.yml: add packages build workflow

build.yml: add linux package builds

---

.github/workflows/build.yml

We need a branch to publish a special release for testing purpose (nightly/prerelease)
None

Add a new `develop` branch, publish a `prerelease` Github Release

---

docs/build.md
docs/getting-started.md

- docs: include a short notes for nightly builds
NA

docs: include a short notes for nightly builds

---

.github/workflows/sync-upstream-source.yml

Apply essential patches to the existing `sync-upstream-source` workflow.
- feat: add pr-base-branch input
- fix: mod default checkout branch; `HEAD` to `origin/HEAD`
- feat: update pr body msg
NA
https://github.com/daeuniverse/daed/actions/runs/5297703050

ci(sync-upstream): general patches

---

docs/getting-started.md

Too lazy to write description. You know ...

docs(getting-started.md): correct a tiny typo

---

.github/workflows/build-nightly.yml

- ci: ignore *.md to trigger build
NA.

ci: ignore *.md to trigger build

---

.github/workflows/build.yml

Fix upload zip files to release

build.yml: Fix upload zip files to release

---

.github/workflows/build.yml

- ci(build): fix missing dependant job
NA

ci(build): fix missing dependant job

---

.github/workflows/sync-upstream-source.yml

As the title suggests. While we are investigating the root cause, let's sync the submodule ref manually this time. Just don't want to lag too far behind.

ci: fix sync upstream

---

.github/workflows/build.yml
install/package_after_install.sh
install/package_after_remove.sh
install/package_before_remove.sh

Remove redundant paths for zip archives

ci(build.yml): Remove redundant paths for zip archives

---

install/daed.service

Systemd service is out of date, this PR fix that
- fix: systemd service file description and service start command
None

fix: systemd service file description and service start command

---

CHANGELOGS.md

Update exiting changelogs for `release-v0.1.0rc`.
- chore(release-v0.1.0rc): update release changelogs
NA.

chore(release-v0.1.0rc): update release changelogs

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support-request.md

- fix(issue-template): update default labels for bug-report
- fix(issue-template): update default labels for enhancement
- fix(issue-template): update default labels for feature-request
- fix(issue-template): update default labels for support-request

chore(issue-template): update default labels for bug-report

---

.github/workflows/prerelease.yml

As the title suggests - include (e.g. v0.1.1rc1) case
- ci(prerelease): catch v*.*.*rc* (v0.1.1rc1) case
NA

ci(prerelease): include v*.*.*rc* (v0.1.1rc1) case

---

src/pages/Orchestrate/Node.tsx
src/pages/Orchestrate/Subscription.tsx
src/pages/Orchestrate/index.tsx

[Peek 2023-06-21 09-37.webm](https://github.com/daeuniverse/daed/assets/17328586/97b3f1b0-8899-424e-8602-26d83f0b0849)
- fix: dragging not working properly
None

fix: dragging not working properly

---

src/components/Header.tsx
src/i18n/locales/en.json
src/i18n/locales/zh-Hans.json

This PR adds a new feature, show tooltip on header actions hover (running toggle, reload)
- feat: add tooltip for header actions
None

feat: add tooltip for header actions

---

CHANGELOGS.md

- hotfix(changelogs/v0.1.0rc): fix formatting
NA

hotfix(changelogs/v0.1.0rc): fix formatting

---

src/components/PlainTextFormModal.tsx
src/constants/index.ts
src/main.tsx
src/pages/Experiment.tsx

This PR Imported missing packages necessary for setting fontFamily to monospace

fix: import missing packages and clean up unreference files

---

README.md

- docs(readme): add release badge
NA

docs(readme): add release badge

---

CHANGELOGS.md

Due to some technical issue, we got to do the release manually this time.
- chore(changelogs): add entry for v0.1.1
NA

release: draft release for v0.1.1

---

src/components/Section.tsx
src/components/SimpleCard.tsx
src/components/UpdateSubscriptionAction.tsx
src/pages/Orchestrate/Node.tsx
src/pages/Orchestrate/Subscription.tsx

feat: change icons

---

.github/workflows/publish-docker-image.yml
Dockerfile
src/components/Header.tsx
src/vite-env.d.ts
vite.config.ts

This PR adds support for ghcr.io docker image
- build: publish `ghcr.io` docker image
None

ci(build): publish `ghcr.io` docker image

---

.github/workflows/sync-upstream.yml

Add modularity support for `sync-upstream` workflow; also see https://github.com/daeuniverse/dae-bot/pull/67
- ci(sync-upstream) apply modularity support
NA.
Ref: https://github.com/daeuniverse/dae-wing/pull/64
Workflow run: https://github.com/daeuniverse/dae-wing/actions/runs/5516748359

ci(sync-upstream) apply modularity support

---

.github/workflows/build.yml

To reduce confusion, builds in `main` branch are NOT always stable.
- ci(build): rename Build (Stable) -> Build (Main)
NA
NA

ci(build): rename Build (Stable) -> Build (Main)

---

.github/workflows/pr-build.yml

- ci/chore(pr-build): remove unnecessary lines
NA
NA

ci/chore(pr-build): remove unnecessary lines

---

package.json
pnpm-lock.yaml
src/utils/helper.ts
src/utils/index.test.ts
tsconfig.json
vite.config.ts

This PR fixes a issue, when the graphql returns a time unit bigger than seconds (s), the parsing result is wrong
- fix: time parsing is wrong
None

fix: time parsing is wrong

---

README.md

Add build-status badge
- docs(readme): add build-status badge
NA

docs(readme): add build-status badge

---

.husky/pre-commit
package.json

- chore: run unite tests before commiting
None

chore: run unite tests before commiting

---

CHANGELOGS.md

Due to some technical issue, we got to do the release manually this time.
- docs: update CHANGELOGS.md
NA

release: draft release for v0.2.0

---

.github/workflows/build.yml
.github/workflows/pr-build.yml

This PR proposes changes to To better constrain the condition to trigger the `pr-build`.
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths
- ci(pr-build): update trigger paths
NA
NA

ci(pr-build): update trigger paths

---

.github/workflows/pr-build.yml
src/App.tsx
src/components/DraggableResourceBadge.tsx
src/components/Header.tsx
src/pages/Experiment.tsx

This PR fixes an issue, reload icon not showing on small size screens
- fix: reload icon not showing on small size screens

fix: reload icon not showing on small size screens

---

src/components/ConfigureNodeFormModal/JuicityForm.tsx
src/components/ConfigureNodeFormModal/index.tsx
src/constants/default.ts
src/constants/schema.ts

- feat: add configure juicity modal
None

feat: add configure juicity modal

---

.github/workflows/generate-changelogs.yml

- ci(generate-changelogs): fix dry_run input description
NA
NA

ci/fix(generate-changelogs): fix dry_run input description

---

.github/PULL_REQUEST_TEMPLATE.md

- chore(pr_template): fix a typo 

chore(pr_template): fix typo

---

src/App.tsx

This PR adds a new feature, set color scheme based on system preference
When a user changes the system prefered color scheme setting, set to light/dark mode automatically
- feat: set color scheme based on system preference

feat: set color scheme based on system preference

---

src/apis/mutation.ts

- feat: disable rollbackError, fixes #207
Closes #207

feat: disable rollbackError, fixes #207

---

.github/PULL_REQUEST_TEMPLATE.md

Update pr_template section headers.

chore(pr_template): update section headers

---

.github/workflows/build.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml

**This should be merged after <https://github.com/daeuniverse/dae-wing/pull/100>.**

chore: support build_mode=pie

---

.github/workflows/pick-build.yml

ci(pick): fix build failure due to go mod not being updated

---

src/constants/default.ts

- feat(routing): add dnsmasq to must_direct default routing
NA
NA

feat(routing): add dnsmasq to must_direct default routing

---

.github/workflows/generate-changelogs.yml

Update default assignee from @daebot to ["yqlbu","mzz2017","kunish"]
- ci(generate-changelogs): update default assignees list

ci(generate-changelogs): update default assignees list

---

.github/workflows/build.yml
.github/workflows/generate-changelogs.yml
.github/workflows/pick-build.yml
.github/workflows/pr-build.yml
.github/workflows/prerelease.yml
.github/workflows/publish-docker-image.yml
.github/workflows/publish-gh-pages.yml
.github/workflows/release.yml
.vscode/settings.json

ci: update ci modules to the latest version

---

.github/workflows/pick-build.yml

See: https://github.com/daeuniverse/daed-1/actions/runs/9534418011

ci/feat: support customized git remote for Pick Build

---

CHANGELOGS.md

ci(release): draft release v0.7.0rc1

---

publish.Dockerfile

ci(docker): update go version to 1.22

---

CHANGELOGS.md

ci(release): draft release v0.7.0rc1.1

---

src/components/ConfigureNodeFormModal/Hysteria2Form.tsx

https://github.com/daeuniverse/daed/pull/440#discussion_r1763770670
https://v2.hysteria.network/zh/docs/developers/URI-Scheme/

fix(hy2): insecure parameter not work

---

src/components/ImportResourceFormModal.tsx

fix(import): cannot import node

---

docs/getting-started.md

- Add [Fedora Copr](https://copr.fedorainfracloud.org/coprs/zhullyb/v2rayA/package/daed) to Quick Start Guide

docs: add Fedora Copr to Quick Start Guide
